services:
  # Base de Datos MySQL
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: agprueba
      # MYSQL_USER: ${DB_USER}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Servidor de Autorización
  auth-server:
    build: ./authorization-server
    container_name: auth-server
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      # Conectamos a 'mysql-db' en lugar de localhost
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/agprueba?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      # Aquí ponemos las claves de Google OAuth2S
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    ports:
      - "9000:9000" # Puerto correcto según tu archivo properties
    networks:
      - app-network
    healthcheck:
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/9000'"
      interval: 10s
      timeout: 5s
      retries: 10

  # Servidor de Recursos
  resource-server:
    build: ./resource-server
    container_name: resource-server
    restart: on-failure
    depends_on:
      mysql-db:
        condition: service_healthy
      auth-server:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/agprueba?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}      
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://auth-server:9000
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://auth-server:9000/oauth2/jwks
    ports:
      - "8081:8080"
    networks:
      - app-network

  # Frontend Angular
  frontend:
    build: ./ag-prueba-front
    container_name: angular-front
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

    